#!/usr/bin/env node
// gen_vk_rs.js — Convert snarkjs verification_key.json to Rust constants
// Usage: node gen_vk_rs.js <verification_key.json>

const fs = require("fs");
const path = require("path");

const vkPath = process.argv[2];
if (!vkPath) {
  console.error("Usage: node gen_vk_rs.js <verification_key.json>");
  process.exit(1);
}

const vk = JSON.parse(fs.readFileSync(vkPath, "utf-8"));

// Convert decimal string to 32-byte big-endian
function toBytes32BE(dec) {
  let hex = BigInt(dec).toString(16);
  if (hex.length > 64) throw new Error("Value too large for 32 bytes: " + hex);
  hex = hex.padStart(64, "0");
  const bytes = [];
  for (let i = 0; i < 64; i += 2) {
    bytes.push(parseInt(hex.substring(i, i + 2), 16));
  }
  return bytes;
}

// G1 point: [x, y, z] → 64 bytes (x_BE + y_BE)
function g1ToBytes(arr) {
  const x = toBytes32BE(arr[0]);
  const y = toBytes32BE(arr[1]);
  return [...x, ...y];
}

// G2 point: [[x0,x1],[y0,y1],[z0,z1]] → 128 bytes
// Solana format: x_c0 | x_c1 | y_c0 | y_c1
function g2ToBytes(arr) {
  const x0 = toBytes32BE(arr[0][0]);
  const x1 = toBytes32BE(arr[0][1]);
  const y0 = toBytes32BE(arr[1][0]);
  const y1 = toBytes32BE(arr[1][1]);
  return [...x0, ...x1, ...y0, ...y1];
}

function fmtBytes(arr) {
  const lines = [];
  for (let i = 0; i < arr.length; i += 16) {
    const chunk = arr.slice(i, i + 16);
    lines.push("    " + chunk.map(b => "0x" + b.toString(16).padStart(2, "0")).join(", ") + ",");
  }
  return lines.join("\n");
}

function fmtG1(arr) {
  return `[\n${fmtBytes(g1ToBytes(arr))}\n]`;
}

function fmtG2(arr) {
  return `[\n${fmtBytes(g2ToBytes(arr))}\n]`;
}

// Generate Rust code
const alphaG1 = fmtG1(vk.vk_alpha_1);
const betaG2 = fmtG2(vk.vk_beta_2);
const gammaG2 = fmtG2(vk.vk_gamma_2);
const deltaG2 = fmtG2(vk.vk_delta_2);
const icCount = vk.IC.length;

const icEntries = vk.IC.map((point, i) => {
  return `    // IC[${i}]${i === 0 ? " (constant term)" : ` (public input ${i})`}\n    ${fmtG1(point)}`;
});

const rust = `// Auto-generated by scripts/gen_vk_rs.js
// DO NOT EDIT MANUALLY — re-run after trusted setup

pub const ALPHA_G1: [u8; 64] = ${alphaG1};

pub const BETA_G2: [u8; 128] = ${betaG2};

pub const GAMMA_G2: [u8; 128] = ${gammaG2};

pub const DELTA_G2: [u8; 128] = ${deltaG2};

pub const IC: [[u8; 64]; ${icCount}] = [
${icEntries.join(",\n")}
];
`;

// Write output
const outPath = path.join(path.dirname(vkPath), "..", "..", "programs", "zk_verifier", "src", "vk.rs");
fs.writeFileSync(outPath, rust);
console.log(`Written to ${outPath}`);
console.log(`IC count: ${icCount} (1 constant + ${icCount - 1} public inputs)`);
