//! Baby Jubjub BSGS decryption for Nexum Audit Oracle
//!
//! Implements ElGamal ciphertext decryption over the Baby Jubjub curve
//! using brute-force search in [0, 65536) for hackathon demo purposes.

#![allow(dead_code)]

use num_bigint::{BigInt, Sign};
use num_integer::Integer;
use num_traits::{One, ToPrimitive, Zero};
use std::collections::HashMap;

// ── Baby Jubjub curve parameters ────────────────────────────────────────────

/// Field modulus p for Baby Jubjub (same as BN254 scalar field)
pub const FIELD_MODULUS: &str =
    "21888242871839275222246405745257275088548364400416034343698204186575808495617";

/// Subgroup order (prime, size of the cyclic group generated by G)
pub const CURVE_ORDER: &str =
    "2736030358979909402780800718157159386076813972158567259200215660948447373041";

/// Generator G x-coordinate
pub const GENERATOR_X: &str =
    "7582035475627193640797276505418002166691739036475590846121162698650004832581";

/// Generator G y-coordinate
pub const GENERATOR_Y: &str =
    "7801528930831391612913542953849263092120765287178679640990215688947513841260";

/// Curve parameter a = 168700
pub const CURVE_A: &str = "168700";

/// Curve parameter d = 168696
pub const CURVE_D: &str = "168696";

/// Hackathon demo search range
pub const SEARCH_RANGE: u64 = 65536;

// ── Lazy statics for BigInt constants ────────────────────────────────────────

pub struct CurveParams {
    pub p: BigInt,          // field modulus
    pub order: BigInt,      // subgroup order
    pub a: BigInt,          // curve param a
    pub d: BigInt,          // curve param d
    pub gx: BigInt,         // generator x
    pub gy: BigInt,         // generator y
    pub p_minus_1: BigInt,  // p - 1
    pub p_minus_2: BigInt,  // p - 2
}

impl CurveParams {
    pub fn new() -> Self {
        let p = BigInt::parse_bytes(FIELD_MODULUS.as_bytes(), 10).unwrap();
        let order = BigInt::parse_bytes(CURVE_ORDER.as_bytes(), 10).unwrap();
        let a = BigInt::parse_bytes(CURVE_A.as_bytes(), 10).unwrap();
        let d = BigInt::parse_bytes(CURVE_D.as_bytes(), 10).unwrap();
        let gx = BigInt::parse_bytes(GENERATOR_X.as_bytes(), 10).unwrap();
        let gy = BigInt::parse_bytes(GENERATOR_Y.as_bytes(), 10).unwrap();
        let p_minus_1 = &p - 1;
        let p_minus_2 = &p - 2;
        Self {
            p,
            order,
            a,
            d,
            gx,
            gy,
            p_minus_1,
            p_minus_2,
        }
    }
}

// ── Affine point on Baby Jubjub ─────────────────────────────────────────────

#[derive(Clone, Debug)]
pub struct Point {
    pub x: BigInt,
    pub y: BigInt,
}

impl Point {
    pub fn zero() -> Self {
        Point {
            x: BigInt::zero(),
            y: BigInt::one(),
        }
    }

    pub fn is_zero(&self) -> bool {
        self.x.is_zero() && self.y.is_one()
    }
}

impl PartialEq for Point {
    fn eq(&self, other: &Self) -> bool {
        self.x == other.x && self.y == other.y
    }
}

// ── Extended point for fast arithmetic ──────────────────────────────────────

/// Extended coordinates (X, Y, Z, T) where x = X/Z, y = Y/Z, T = X*Y/Z
#[derive(Clone, Debug)]
pub struct ExtendedPoint {
    pub x: BigInt,
    pub y: BigInt,
    pub z: BigInt,
    pub t: BigInt,
}

impl ExtendedPoint {
    pub fn from_affine(p: &Point, params: &CurveParams) -> Self {
        ExtendedPoint {
            x: p.x.clone(),
            y: p.y.clone(),
            z: BigInt::one(),
            t: (&p.x * &p.y) % &params.p,
        }
    }

    pub fn to_affine(&self, params: &CurveParams) -> Point {
        if self.z.is_zero() {
            return Point::zero();
        }
        let z_inv = mod_inv(&self.z, &params.p);
        let x = (&self.x * &z_inv) % &params.p;
        let y = (&self.y * &z_inv) % &params.p;
        Point { x, y }
    }

    pub fn is_zero(&self) -> bool {
        self.z.is_zero()
    }

    /// Extended twisted Edwards unified addition for curve a*x^2 + y^2 = 1 + d*x^2*y^2.
    ///
    /// Using the standard formulas from https://hyperelliptic.org/EFD/g1p/auto-twisted-extended.html:
    ///   A = X1*X2
    ///   B = Y1*Y2
    ///   C = T1*d*T2
    ///   D = Z1*Z2
    ///   E = (X1+Y1)*(X2+Y2) - A - B
    ///   F = D - C
    ///   G = D + C
    ///   H = B - a*A
    ///   X3 = E*F
    ///   Y3 = G*H
    ///   T3 = E*H
    ///   Z3 = F*G
    pub fn add(&self, other: &ExtendedPoint, params: &CurveParams) -> ExtendedPoint {
        // Handle identity (Z=0) special cases
        if self.z.is_zero() {
            return other.clone();
        }
        if other.z.is_zero() {
            return self.clone();
        }

        let p = &params.p;

        let a_val = (&self.x * &other.x) % p;
        let b_val = (&self.y * &other.y) % p;
        let c_val = ((&self.t * &other.t) % p * &params.d) % p;
        let d_val = (&self.z * &other.z) % p;

        let e_val = ((&self.x + &self.y) * (&other.x + &other.y) % p - &a_val - &b_val.clone() + p + p) % p;
        let f_val = (&d_val - &c_val + p) % p;
        let g_val = (&d_val + &c_val) % p;
        let h_val = (&b_val - &params.a * &a_val % p + p) % p;

        ExtendedPoint {
            x: (&e_val * &f_val) % p,
            y: (&g_val * &h_val) % p,
            z: (&f_val * &g_val) % p,
            t: (&e_val * &h_val) % p,
        }
    }

    /// Point doubling (same as add with self, but we use generic add)
    pub fn double(&self, params: &CurveParams) -> ExtendedPoint {
        self.add(self, params)
    }

    /// Scalar multiplication using double-and-add
    pub fn scalar_mul(&self, scalar: &BigInt, params: &CurveParams) -> ExtendedPoint {
        if scalar.is_zero() {
            return ExtendedPoint {
                x: BigInt::zero(),
                y: BigInt::one(),
                z: BigInt::zero(),
                t: BigInt::zero(),
            };
        }

        let mut result = ExtendedPoint {
            x: BigInt::zero(),
            y: BigInt::one(),
            z: BigInt::zero(),
            t: BigInt::zero(),
        };
        let mut base = self.clone();
        let mut k = scalar.clone();

        // Handle negative scalars
        if k.sign() == Sign::Minus {
            k = -k;
            base = base.negate(params);
        }

        while !k.is_zero() {
            if k.is_odd() {
                result = result.add(&base, params);
            }
            base = base.add(&base, params);
            k >>= 1;
        }
        result
    }

    /// Negate a point: -(X:Y:Z:T) = (-X:Y:Z:-T)
    pub fn negate(&self, params: &CurveParams) -> ExtendedPoint {
        ExtendedPoint {
            x: (&params.p - &self.x) % &params.p,
            y: self.y.clone(),
            z: self.z.clone(),
            t: (&params.p - &self.t) % &params.p,
        }
    }

    /// Subtract: self - other = self + (-other)
    pub fn subtract(&self, other: &ExtendedPoint, params: &CurveParams) -> ExtendedPoint {
        self.add(&other.negate(params), params)
    }
}

// ── ElGamal ciphertext ──────────────────────────────────────────────────────

#[derive(Clone, Debug)]
pub struct Ciphertext {
    pub c1: Point,
    pub c2: Point,
}

// ── Modular inverse using Fermat's little theorem ───────────────────────────

pub fn mod_inv(a: &BigInt, p: &BigInt) -> BigInt {
    if a.is_zero() {
        panic!("Cannot invert zero");
    }
    a.modpow(&(&*p - BigInt::from(2u64)), p)
}

// ── Finite field arithmetic helpers ─────────────────────────────────────────

/// Reduce a BigInt into [0, p)
pub fn fe_normalize(v: &BigInt, p: &BigInt) -> BigInt {
    let mut r = v % p;
    if r.sign() == Sign::Minus {
        r = r + p;
    }
    r
}

// ── Generator convenience ───────────────────────────────────────────────────

pub fn generator(params: &CurveParams) -> ExtendedPoint {
    ExtendedPoint::from_affine(
        &Point {
            x: params.gx.clone(),
            y: params.gy.clone(),
        },
        params,
    )
}

// ── BSGS decryption ─────────────────────────────────────────────────────────

/// Decrypt an ElGamal ciphertext by brute-force search in [0, range).
///
/// Given ciphertext (C1, C2) where:
///   C1 = r*G
///   C2 = m*G + r*pk
/// and secret key `sk` where pk = sk*G:
///
/// Compute mG = C2 - sk*C1, then search for m by computing i*G for i in [0, range)
/// and checking equality.
pub fn decrypt_audit_ciphertext(
    ct: &Ciphertext,
    audit_sk: &BigInt,
    params: &CurveParams,
    range: u64,
) -> Result<u64, String> {
    let g = generator(params);

    // Compute mG = C2 - sk*C1
    let c1_ext = ExtendedPoint::from_affine(&ct.c1, params);
    let c2_ext = ExtendedPoint::from_affine(&ct.c2, params);

    let sk_c1 = c1_ext.scalar_mul(audit_sk, params);
    let mg = c2_ext.subtract(&sk_c1, params);
    let mg_affine = mg.to_affine(params);

    // Check if mG is identity (m=0)
    if mg_affine.is_zero() {
        return Ok(0);
    }

    // Brute force: compute i*G for i = 1..range-1 and check
    // Use incremental addition: (i+1)*G = i*G + G
    let g_affine = g.to_affine(params);
    let mut current = g_affine.clone(); // 1*G

    for i in 1u64..range {
        if current == mg_affine {
            return Ok(i);
        }
        // current = (i+1)*G = i*G + G
        let current_ext = ExtendedPoint::from_affine(&current, params);
        let next_ext = current_ext.add(&g, params);
        current = next_ext.to_affine(params);
    }

    // Also check the last iteration
    if current == mg_affine {
        return Ok(range - 1);
    }

    Err(format!(
        "BSGS decrypt failed: value not in range [0, {})",
        range
    ))
}

/// Build a BSGS baby-step table for faster lookup.
/// Returns a HashMap from (x-coordinate low 64 bits) -> i, and the giant step point.
pub fn build_baby_step_table(
    params: &CurveParams,
    table_size: u64,
) -> (HashMap<u64, u64>, Point) {
    let g = generator(params);

    // Giant step = TABLE_SIZE * G
    let giant_step_ext = g.scalar_mul(&BigInt::from(table_size), params);
    let giant_step = giant_step_ext.to_affine(params);

    let mut table = HashMap::new();
    let mut current = g.to_affine(params); // 1*G

    for i in 1u64..table_size {
        // Use low 64 bits of x-coordinate as hash key
        let key = point_hash_key(&current, params);
        table.insert(key, i);

        // Advance: current = current + G
        let cur_ext = ExtendedPoint::from_affine(&current, params);
        let next_ext = cur_ext.add(&g, params);
        current = next_ext.to_affine(params);
    }

    (table, giant_step)
}

/// BSGS decrypt with precomputed baby-step table.
/// Search range: [0, table_size * table_size)
pub fn bsgs_decrypt_with_table(
    ct: &Ciphertext,
    audit_sk: &BigInt,
    params: &CurveParams,
    baby_table: &HashMap<u64, u64>,
    giant_step: &Point,
    table_size: u64,
) -> Result<u64, String> {
    // Compute mG = C2 - sk*C1
    let c1_ext = ExtendedPoint::from_affine(&ct.c1, params);
    let c2_ext = ExtendedPoint::from_affine(&ct.c2, params);

    let sk_c1 = c1_ext.scalar_mul(audit_sk, params);
    let mg = c2_ext.subtract(&sk_c1, params);
    let mg_affine = mg.to_affine(params);

    // Check m=0
    if mg_affine.is_zero() {
        return Ok(0);
    }

    // Giant step: negate the giant step point
    let gs_ext = ExtendedPoint::from_affine(giant_step, params);
    let _gs_neg = gs_ext.negate(params);

    let mut cursor = mg.clone();

    for j in 0u64..table_size {
        let cursor_affine = cursor.to_affine(params);

        // Check if cursor is identity
        if cursor_affine.is_zero() {
            return Ok(j * table_size);
        }

        // Look up in baby-step table
        let key = point_hash_key(&cursor_affine, params);
        if let Some(&i) = baby_table.get(&key) {
            let m = j * table_size + i;
            return Ok(m);
        }

        // Giant step: cursor = cursor - giantStep
        cursor = cursor.subtract(&gs_ext, params);
    }

    Err(format!(
        "BSGS decrypt failed: value not in range [0, {})",
        table_size * table_size
    ))
}

/// Hash key for a point: low 64 bits of x-coordinate
fn point_hash_key(p: &Point, params: &CurveParams) -> u64 {
    // Take x mod 2^64
    let x_mod = &p.x % &params.p;
    let mask = BigInt::from(u64::MAX);
    let low64 = &x_mod & &mask;
    let (_, digits) = low64.to_u64_digits();
    if digits.is_empty() {
        0
    } else {
        digits[0]
    }
}

// ── Serialization helpers ───────────────────────────────────────────────────

/// Parse a 32-byte little-endian buffer into a BigInt
pub fn read_bigint_32le(buf: &[u8]) -> BigInt {
    let mut n = BigInt::zero();
    for i in 0..32 {
        n = n + (BigInt::from(buf[i]) << (i * 8));
    }
    n
}

/// Write a BigInt into a 32-byte little-endian buffer
pub fn write_bigint_32le(val: &BigInt, buf: &mut [u8; 32]) {
    for i in 0..32 {
        let byte_val: BigInt = (val >> (i * 8)) & BigInt::from(0xFFu8);
        buf[i] = byte_val.to_u8().unwrap_or(0);
    }
}

/// Deserialize a ciphertext from 128 bytes (4 x 32-byte LE BigInts)
pub fn deserialize_ciphertext(buf: &[u8]) -> Result<Ciphertext, String> {
    if buf.len() != 128 {
        return Err(format!(
            "Invalid ciphertext length: expected 128, got {}",
            buf.len()
        ));
    }
    Ok(Ciphertext {
        c1: Point {
            x: read_bigint_32le(&buf[0..32]),
            y: read_bigint_32le(&buf[32..64]),
        },
        c2: Point {
            x: read_bigint_32le(&buf[64..96]),
            y: read_bigint_32le(&buf[96..128]),
        },
    })
}

/// Serialize a ciphertext into 128 bytes
pub fn serialize_ciphertext(ct: &Ciphertext) -> [u8; 128] {
    let mut buf = [0u8; 128];
    write_bigint_32le(&ct.c1.x, (&mut buf[0..32]).try_into().unwrap());
    write_bigint_32le(&ct.c1.y, (&mut buf[32..64]).try_into().unwrap());
    write_bigint_32le(&ct.c2.x, (&mut buf[64..96]).try_into().unwrap());
    write_bigint_32le(&ct.c2.y, (&mut buf[96..128]).try_into().unwrap());
    buf
}

// ── Tests ────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generator_on_curve() {
        let params = CurveParams::new();
        let g = generator(&params);
        let affine = g.to_affine(&params);

        // Verify a*x^2 + y^2 = 1 + d*x^2*y^2 (mod p)
        let x2 = &affine.x * &affine.x % &params.p;
        let y2 = &affine.y * &affine.y % &params.p;
        let lhs = (&params.a * &x2 + &y2) % &params.p;
        let rhs = (BigInt::one() + &params.d * &x2 % &params.p * &y2 % &params.p) % &params.p;
        assert_eq!(lhs, rhs, "Generator point is not on the curve");
    }

    #[test]
    fn test_scalar_mul_identity() {
        let params = CurveParams::new();
        let g = generator(&params);

        // 0 * G should be identity
        let zero = g.scalar_mul(&BigInt::zero(), &params);
        assert!(zero.to_affine(&params).is_zero());
    }

    #[test]
    fn test_scalar_mul_generator() {
        let params = CurveParams::new();
        let g = generator(&params);

        // 1 * G should equal G
        let one_g = g.scalar_mul(&BigInt::one(), &params);
        assert_eq!(one_g.to_affine(&params), g.to_affine(&params));
    }

    #[test]
    fn test_encrypt_decrypt_roundtrip() {
        let params = CurveParams::new();
        let g = generator(&params);

        // Use a small secret key
        let sk = BigInt::from(12345u64);
        let pk_ext = g.scalar_mul(&sk, &params);
        let pk = pk_ext.to_affine(&params);

        // Encrypt m = 42: C1 = r*G, C2 = m*G + r*pk
        let m: u64 = 42;
        let r = BigInt::from(99999u64);

        let c1_ext = g.scalar_mul(&r, &params);
        let c1 = c1_ext.to_affine(&params);

        let mg_ext = g.scalar_mul(&BigInt::from(m), &params);
        let rpk_ext = ExtendedPoint::from_affine(&pk, &params).scalar_mul(&r, &params);
        let c2_ext = mg_ext.add(&rpk_ext, &params);
        let c2 = c2_ext.to_affine(&params);

        let ct = Ciphertext { c1, c2 };

        // Decrypt
        let decrypted =
            decrypt_audit_ciphertext(&ct, &sk, &params, SEARCH_RANGE).expect("decrypt failed");
        assert_eq!(decrypted, m);
    }

    #[test]
    fn test_encrypt_decrypt_zero() {
        let params = CurveParams::new();
        let g = generator(&params);

        let sk = BigInt::from(54321u64);
        let pk_ext = g.scalar_mul(&sk, &params);
        let pk = pk_ext.to_affine(&params);

        let r = BigInt::from(77777u64);

        // m = 0: C2 = r*pk (no m*G term)
        let c1_ext = g.scalar_mul(&r, &params);
        let c1 = c1_ext.to_affine(&params);

        let rpk_ext = ExtendedPoint::from_affine(&pk, &params).scalar_mul(&r, &params);
        let c2 = rpk_ext.to_affine(&params);

        let ct = Ciphertext { c1, c2 };

        let decrypted =
            decrypt_audit_ciphertext(&ct, &sk, &params, SEARCH_RANGE).expect("decrypt failed");
        assert_eq!(decrypted, 0);
    }

    #[test]
    fn test_bsgs_with_table_roundtrip() {
        let params = CurveParams::new();
        let g = generator(&params);

        let sk = BigInt::from(11111u64);
        let pk_ext = g.scalar_mul(&sk, &params);
        let pk = pk_ext.to_affine(&params);

        let table_size = 256u64; // small table for test speed
        let (baby_table, giant_step) = build_baby_step_table(&params, table_size);

        // Test m = 1000 (within range 0..256*256=65536)
        let m: u64 = 1000;
        let r = BigInt::from(88888u64);

        let c1_ext = g.scalar_mul(&r, &params);
        let c1 = c1_ext.to_affine(&params);

        let mg_ext = g.scalar_mul(&BigInt::from(m), &params);
        let rpk_ext = ExtendedPoint::from_affine(&pk, &params).scalar_mul(&r, &params);
        let c2_ext = mg_ext.add(&rpk_ext, &params);
        let c2 = c2_ext.to_affine(&params);

        let ct = Ciphertext { c1, c2 };

        let decrypted = bsgs_decrypt_with_table(
            &ct,
            &sk,
            &params,
            &baby_table,
            &giant_step,
            table_size,
        )
        .expect("BSGS decrypt failed");
        assert_eq!(decrypted, m);
    }

    #[test]
    fn test_serialization_roundtrip() {
        let params = CurveParams::new();
        let g = generator(&params);

        let r = BigInt::from(12345u64);
        let m = BigInt::from(999u64);
        let sk = BigInt::from(7777u64);
        let pk_ext = g.scalar_mul(&sk, &params);
        let pk = pk_ext.to_affine(&params);

        let c1 = g.scalar_mul(&r, &params).to_affine(&params);
        let mg_ext = g.scalar_mul(&m, &params);
        let rpk_ext = ExtendedPoint::from_affine(&pk, &params).scalar_mul(&r, &params);
        let c2 = mg_ext.add(&rpk_ext, &params).to_affine(&params);

        let ct = Ciphertext { c1, c2 };

        let serialized = serialize_ciphertext(&ct);
        let deserialized = deserialize_ciphertext(&serialized).unwrap();

        assert_eq!(ct.c1.x, deserialized.c1.x);
        assert_eq!(ct.c1.y, deserialized.c1.y);
        assert_eq!(ct.c2.x, deserialized.c2.x);
        assert_eq!(ct.c2.y, deserialized.c2.y);
    }
}
