use anchor_lang::prelude::*;

declare_id!("EArRMxL5MSNTXRt4D9wv5MfrXYifhUSzAXbUiaqKMt3U");

// ── Verification key (auto-generated by scripts/gen_vk_rs.js) ──
mod vk;
mod alt_bn128;

#[program]
pub mod zk_verifier {
    use super::*;

    /// Verify a balance_transition Groth16 proof on-chain
    /// proof_bytes: 256 bytes (A:64 + B:128 + C:64)
    /// pub_inputs:  30 × 32 = 960 bytes (LE BN254 scalars)
    pub fn verify_balance_transition(
        _ctx: Context<VerifyProof>,
        proof_bytes: [u8; 256],
        pub_inputs: Vec<u8>,
    ) -> Result<()> {
        let _ = _ctx.remaining_accounts; // No specific accounts needed
        require!(
            pub_inputs.len() == 30 * 32,
            VerifierError::InvalidPublicInputsLength
        );

        // 1. Deserialize proof
        let proof_a = &proof_bytes[0..64];
        let proof_b = &proof_bytes[64..192];
        let proof_c = &proof_bytes[192..256];

        // 2. Compute vk_x = IC[0] + Σ(pub_input[i] × IC[i+1])
        let mut vk_x = vk::IC[0].to_vec();
        for i in 0..30 {
            let input = &pub_inputs[i * 32..(i + 1) * 32];
            let ic_i = &vk::IC[i + 1];

            // G1 scalar multiplication: input × IC[i+1]
            let mut mult_input = [0u8; 96];
            mult_input[..32].copy_from_slice(input);
            mult_input[32..96].copy_from_slice(ic_i);

            let scaled = alt_bn128::alt_bn128_multiplication(&mult_input)
                .map_err(|_| VerifierError::AltBn128Error)?;

            // G1 addition: vk_x += scaled
            let mut add_input = [0u8; 128];
            add_input[..64].copy_from_slice(&vk_x);
            add_input[64..].copy_from_slice(&scaled);

            vk_x = alt_bn128::alt_bn128_addition(&add_input)
                .map_err(|_| VerifierError::AltBn128Error)?
                .to_vec();
        }

        // 3. Build pairing check input (4 pairs)
        // Verify: e(-proof_a, proof_b) × e(alpha, beta) × e(vk_x, gamma) × e(proof_c, delta) = 1
        let neg_proof_a = negate_g1(proof_a)?;

        let mut pairing_input = Vec::with_capacity(4 * 192);
        pairing_input.extend_from_slice(&neg_proof_a);
        pairing_input.extend_from_slice(proof_b);
        pairing_input.extend_from_slice(&vk::ALPHA_G1);
        pairing_input.extend_from_slice(&vk::BETA_G2);
        pairing_input.extend_from_slice(&vk_x);
        pairing_input.extend_from_slice(&vk::GAMMA_G2);
        pairing_input.extend_from_slice(proof_c);
        pairing_input.extend_from_slice(&vk::DELTA_G2);

        // 4 pairing checks
        let result = alt_bn128::alt_bn128_pairing(&pairing_input)
            .map_err(|_| VerifierError::AltBn128Error)?;

        // Result should be 1 (unit element in pairing target group)
        let expected = {
            let mut r = [0u8; 32];
            r[31] = 1; // LE representation of 1
            r
        };

        require!(
            result == expected,
            VerifierError::ProofInvalid
        );

        Ok(())
    }
}

/// Negate a G1 point (y -> p - y)
fn negate_g1(point: &[u8]) -> Result<[u8; 64]> {
    // BN254 base field prime
    let p: [u8; 32] = [
        0x99, 0x5d, 0x57, 0x91, 0x67, 0x61, 0x94, 0xd7,
        0xb4, 0x69, 0x2b, 0x90, 0x21, 0xb8, 0x98, 0x4b,
        0x3a, 0xf3, 0x75, 0x80, 0xd6, 0x0e, 0xef, 0x91,
        0x97, 0x5a, 0x0c, 0xa1, 0x63, 0x60, 0x7e, 0x01,
    ];

    let mut result = [0u8; 64];
    result[..32].copy_from_slice(&point[..32]); // x unchanged

    // y -> p - y (big-endian subtraction)
    let mut borrow = 0u8;
    for i in (0..32).rev() {
        let (diff, b1) = p[i].overflowing_sub(point[32 + i]);
        let (diff, b2) = diff.overflowing_sub(borrow);
        result[32 + i] = diff;
        borrow = if b1 || b2 { 1 } else { 0 };
    }

    Ok(result)
}

#[derive(Accounts)]
pub struct VerifyProof<'info> {
    /// CHECK: Phantom account — verification-only instruction requires no accounts
    pub _phantom: AccountInfo<'info>,
}

#[error_code]
pub enum VerifierError {
    #[msg("Public inputs length must be 30 × 32 bytes")]
    InvalidPublicInputsLength,
    #[msg("alt_bn128 syscall failed")]
    AltBn128Error,
    #[msg("ZK proof verification failed: pairing check rejected")]
    ProofInvalid,
}
